### ISSUE TITLE
New release for ndarray=0.16.1 please

### ISSUE THREAD

**Issue by pfbuxton** [jonasBoss/ndarray-interp#11]
Hello,

It would be very helpful if we could have a new release built and added to https://crates.io/  to support `ndarray=0.16.1`.

I see that [`cargo.toml`](https://github.com/jonasBoss/ndarray-interp/blob/main/Cargo.toml#L15) has been updated for `ndarray=0.16`. However, the latest 0.4.1 release used `ndarray=0.15`.

The workaround is to clone and install locally:
```bash
git clone https://github.com/jonasBoss/ndarray-interp.git
cd ndarray-interp
cargo build --release
```
then point your own projects `cargo.toml` to use the locally built version:
```toml
[dependencies]
ndarray = "0.16.1"
ndarray-interp = { path = "/path/to/local/ndarray-interp" }
```

Thanks,
Peter
